import streamlit as st
import google.generativeai as genai

# Configurar la API Key de Gemini
API_KEY = st.secrets.get("API_KEY_GEMINI")
if not API_KEY:
    st.error("Error: No se encontró API_KEY_GEMINI en secrets.")
else:
    genai.configure(api_key=API_KEY)

def generar_plan_estudio(edad, nivel, intereses):
    prompt = (f"Genera un plan de estudio personalizado para un estudiante de {edad} años, "
              f"en nivel {nivel}, con intereses en {intereses}. El plan debe ser detallado y estructurado.")
    
    model = genai.GenerativeModel("gemini-2.0-flash")
    response = model.generate_content(prompt)
    return response.text

# Interfaz de Streamlit
st.title("EduAdapt: Personalized Study Plans with AI")
st.sidebar.title("EduAdapt")
st.sidebar.write("Personalized study plans generated by AI")

menu = ["Inicio", "Acerca de nosotros", "Lo que hace la aplicación", "Donación"]
selection = st.sidebar.selectbox("Menu", menu)

if selection == "Inicio":
    st.write("Usamos IA para adaptar el aprendizaje a cada estudiante.")
elif selection == "Acerca de nosotros":
    st.write("EduAdapt es una aplicación creada para ayudar a los estudiantes a obtener planes de estudio personalizados.")
elif selection == "Lo que hace la aplicación":
    st.write("La aplicación genera planes de estudio basados en la edad, el nivel académico y los intereses del estudiante.")
elif selection == "Donación":
    st.write("Si te gusta esta aplicación, por favor considera hacer una donación.")
    # Add a donation button here (e.g., link to a PayPal or Patreon page)
    st.sidebar.button("Donar")


# Entrada del usuario
edad = st.number_input("Edad del estudiante", min_value=3, max_value=100, value=10)
nivel = st.selectbox("Nivel académico", ["Preescolar", "Primaria", "Secundaria", "Universidad"])
intereses = st.text_area("Intereses del estudiante", "Matemáticas, Ciencia, Historia")

if st.button("Generar Plan de Estudio"):
    with st.spinner("Generando plan de estudio..."):
        plan_estudio = generar_plan_estudio(edad, nivel, intereses)
        st.subheader("Plan de Estudio Personalizado")
        st.write(plan_estudio)

st.subheader("¿Cómo funciona EduAdapt?")
st.write("""
EduAdapt utiliza inteligencia artificial para generar planes de estudio personalizados. 
Aquí te explicamos cómo funciona:

1.  **Ingresa la información del estudiante:** Proporciona la edad, el nivel académico y los intereses del estudiante.
2.  **Generación del plan de estudio:** Nuestra IA analiza la información proporcionada y genera un plan de estudio detallado y estructurado.
3.  **Plan de estudio personalizado:** Recibe un plan de estudio adaptado a las necesidades e intereses del estudiante.
""")
